config/routes.rb
Rails.application.routes.draw do

  root :to => 'sessions#create'

  resources :companies do
    resources :projects do
      resources :tasks
    end
  end

  resources :activities

  post 'companies/:id', to: 'companies#add_user'

  patch 'tasks/:id/move', to: 'tasks#move'

  post 'users/accept_invitation/:invitation_id', to: 'users#accept_invitaion'
  post 'users/decline_invitation/:invitation_id', to: 'users#decline_invitaion'

  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'welcome', to: 'sessions#welcome'
  get 'companies', to: 'projects#index'

end

app/models/project.rb
class Project < ApplicationRecord

  belongs_to :company
  has_many :tasks

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, except: [:new, :create]

  def new
    @project = Project.new
    @company = Company.find_by(id: params[:company_id])
  end

  def create
    @project = Project.create(params.require(:project).permit(:name, :description, :company_id, :creator_id))
    redirect_to company_project_path(company_id: params[:company_id], id: @project.id) if @project
  end

  def update
  end

  def delete
  end

  def show
    @company_id = params[:company_id]
    @tasks = Task.where(project_id: @project.id)
  end

  private
  def set_project
    @project = Project.find_by(id: params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/new.html.erb
<h1>Create Project</h1>
<%= form_for [@company, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "border" %>
  <%= f.label :description %>
  <%= f.text_area :description, class: "border" %>
  <%= f.hidden_field :creator_id, value: current_user.id %>
  <%= f.hidden_field :company_id, value: @company.id %>
  <%= f.submit "Projekt erstellen", class: "mt-1.5 transition duration-500 inline-block text-sm px-4 py-2 text-black border-black ease-in-out bg-green-600 hover:bg-black hover:text-white transform hover:-translate-y-1 hover:scale-110 hover:border-transparent rounded border cursor-pointer"%>
<%end%>

app/views/projects/show.html.erb
<h2 class="text-center">Current Tasks:</h2>
<div class="content-center">
  <% Task.statuses.each do |t| %>
    <div class="py-2 inline-block sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <div class="bg-gray-50 px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"><%= I18n.t("task.status_#{t[1]}") %></div>
        <div class="bg-white divide-gray-200">
          <ul id="<%= t[0] %>" class="" data-controller="drag" data-drag-url="/tasks/:id/move">
            <% @tasks.where(status: t[1]).each do |task| %>
              <li data-id="<%= task.id %>" class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 hover:underline">

<!--                <a href="<%#= company_project_task_path(project_id: @project.id, company_id: @company_id, id: task.id) %>">-->
                  <%#= task.name %>
<!--                </a>-->

                <button class="modal-open-<%= task.id %> bg-transparent border border-gray-500 hover:border-indigo-500 text-gray-500 hover:text-indigo-500 font-bold py-2 px-4 rounded-full"><%= task.name %> | <%= task.user.firstname %></button>

              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>


<% @tasks.each do |task| %>
  <!--Modal-->
  <div class="modal-<%= task.id %> opacity-0 pointer-events-none fixed w-full h-full top-0 left-0 flex items-center justify-center">
    <div class="modal-overlay-<%= task.id %> absolute w-full h-full bg-gray-900 opacity-50"></div>

    <div class="modal-container-<%= task.id %> bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">

      <!-- Add margin if you want to see some of the overlay behind the modal-->
      <div class="modal-content-<%= task.id %> py-4 text-left px-6">
        <!--Title-->
        <div class="flex justify-between items-center pb-3">
          <p class="text-2xl font-bold"><%= task.name %></p>
          <div class="modal-close-<%= task.id %> cursor-pointer z-50">
            <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
              <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
            </svg>
          </div>
        </div>

        <!--Body-->

        <span><%= task.description %></span>
        <br>

        <p class="text-2xl font-bold">Kommentare</p>

        <input type="text" class="border border-black" placeholder="Comment..">
        <button class="bg-grey-light hover:bg-grey text-grey-darkest font-bold py-2 px-4 rounded inline-flex items-center">Absenden</button>

        <!--Footer-->
        <div class="flex justify-end pt-2">
          <button class="px-4 bg-transparent p-3 rounded-lg text-indigo-500 hover:bg-gray-100 hover:text-indigo-400 mr-2">Action</button>
          <button class="modal-close-<%= task.id %> px-4 bg-indigo-500 p-3 rounded-lg text-white hover:bg-indigo-400">Close</button>
        </div>

      </div>
    </div>
  </div>

  <script>
      var openmodal_<%= task.id %> = document.querySelector(".modal-open-<%= task.id %>")
      console.log("openmodal_<%= task.id %>");
      //for (var i = 0; i < openmodal_<%= task.id %>.length; i++) {
          openmodal_<%= task.id %>.addEventListener('click', function(event){
              event.preventDefault()
              toggleModal_<%= task.id %>()
          })
      //}

      const overlay_<%= task.id %> = document.querySelector('.modal-overlay-<%= task.id %>')
      overlay_<%= task.id %>.addEventListener('click', toggleModal_<%= task.id %>)

      var closemodal_<%= task.id %> = document.querySelectorAll('.modal-close-<%= task.id %>')
      for (var i = 0; i < closemodal_<%= task.id %>.length; i++) {
          closemodal_<%= task.id %>[i].addEventListener('click', toggleModal_<%= task.id %>)
      }

      document.onkeydown = function(evt) {
          evt = evt || window.event
          var isEscape = false
          if ("key" in evt) {
              isEscape = (evt.key === "Escape" || evt.key === "Esc")
          } else {
              isEscape = (evt.keyCode === 27)
          }
          if (isEscape && document.body.classList.contains('modal-active-<%= task.id %>')) {
              toggleModal()
          }
      };

      function toggleModal_<%= task.id %> () {
          const body = document.querySelector('body')
          const modal = document.querySelector('.modal-<%= task.id %>')
          modal.classList.toggle('opacity-0')
          modal.classList.toggle('pointer-events-none')
          body.classList.toggle('modal-active-<%= task.id %>')
      }
  </script>
<% end %>

<div class="flex justify-center">
  <%= button_to "Create a new Task", new_company_project_task_path(project_id: @project.id,company_id: @company_id), method: :get, class: "mt-1.5 transition duration-500 inline-block text-sm px-4 py-2 text-black border-black ease-in-out bg-green-600 hover:bg-black hover:text-white transform hover:-translate-y-1 hover:scale-110 hover:border-transparent rounded border cursor-pointer" %>
</div>