config/routes.rb
Rails.application.routes.draw do

  root :to => 'sessions#create'

  resources :companies do
    resources :projects do
      resources :tasks
    end
  end

  resources :activities

  post 'companies/:id', to: 'companies#add_user'

  patch 'tasks/:id/move', to: 'tasks#move'

  post 'users/accept_invitation/:invitation_id', to: 'users#accept_invitaion'
  post 'users/decline_invitation/:invitation_id', to: 'users#decline_invitaion'

  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'welcome', to: 'sessions#welcome'
  get 'companies', to: 'projects#index'

end

app/models/company.rb
class Company < ApplicationRecord

  has_many :memberships
  has_many :users, :through => :memberships
  has_many :projects

  def users_accepted
    users = self.memberships.where(status: 'accepted').pluck(:user_id)
    User.where(id: users)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :set_company_and_projects, except: [:new, :create]

  def index
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.create(params.require(:company).permit(:name, :creator_id))
    if @company
      redirect_to company_path(id: @company.id)
    end
  end

  def update
  end

  def show
    @users = User.all.where.not(id: @company.user_ids).where.not(id: @company.creator_id)
  end

  def delete

  end

  def add_user
    @user_to_invite = User.find_by(id: params[:company][:user_ids].to_i)
    Membership.create_invitation(@company, @user_to_invite, 'pending', current_user) if @user_to_invite
    redirect_to company_path(id: @company.id)
  end

  private
  def set_company_and_projects
    @company = Company.find_by(id: params[:id])
    @company_projects = Project.where(company_id: @company.id) if @company
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/new.html.erb
<h1>Create Company</h1>
<%= form_for @company do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "border" %>
  <%= f.hidden_field :creator_id, value: current_user.id %>
  <%= f.submit "Company erstellen"%>
<%end%>

app/views/companies/show.html.erb
<p>This is the company show page</p>


<h2><%= I18n.t 'company.members' %>:</h2>

<ul>
  <% @company.users_accepted.each do |u| %>
    <li><%= u.firstname%>, <%= u.lastname %></li>
  <% end %>
</ul>

<%= form_for @company, method: :post do |f| %>
  <%= f.select(:user_ids, @users.collect{ |u| [u.full_name, u.id] }, include_blank: "Select User") %>
  <%= f.submit "Add User"%>
<% end %>

<h2 class="text-center">Current Projects:</h2>
<div class="flex justify-center">
  <%= button_to "Create a new Project", new_company_project_path(company_id: @company.id), method: :get, class: "mt-1.5 transition duration-500 inline-block text-sm px-4 py-2 text-black border-black ease-in-out bg-green-600 hover:bg-black hover:text-white transform hover:-translate-y-1 hover:scale-110 hover:border-transparent rounded border cursor-pointer" %>
</div>
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
          <tr>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              #
            </th>
            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Name
            </th>
          </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
          <% @company_projects.each_with_index do |project, idx| %>
            <tr>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900"><%= idx %></div>
              </td>
              <td class="px-6 py-4 whitespace-nowrap">
                <div class="text-sm text-gray-900 hover:underline"><a href="<%= company_project_path(id: project.id, company_id: @company.id) %>"><%= project.name %></a></div>
              </td>
            </tr>
          <% end %>

          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>